# Generated by Django 3.0.2 on 2020-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200114_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
